
print("Hi am python younger sister,\nThanks for visiting my p.png.........")
print("\nDo upvote me😍😍😍😍😍😍😍........")
print("\n\n")
print("                 ∆   ∆               ")
print("               (   ∆   )             ")
print("      __________      ____________ ")
print("     (__________ °  ° ____________)")
print("                |    |             ")
print("                |    |             ")
print("                ///\\\\\            ")
print("               ////\\\\\\\            ")
print("              /////\\\\\\\\\           ")
print("             //////\\\\\\\\\\\\          ")
print("            ///////\\\\\\\\\\\\\\         ")
print("           ////////\\\\\\\\\\\\\\\\        ")
print("          /////////\\\\\\\\\\\\\\\\\\       ")
print("         //////////\\\\\\\\\\\\\\\\\\\      ")
print("        /°°°°°°°°°°°°°°°°°°°°\     ")
print("          | |            | |       ")
print("          |__)           |__)      ")
print("\n\n")
print("cutie pie")
